services:
  - type: web
    name: spotify-portfolio-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 8080
      - key: FRONTEND_URL
        value: https://kdavis00.github.io/GCA_KaeD/  # Update this with your GitHub Pages URL